### ISSUE TITLE
Update Airtable Column Names

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-home-api#21]
https://github.com/NYCPlanning/labs-home-api/blob/master/routes/dashboard.js#L24

Airtable columns names have been changed, and need to be updated in the `/dashboard` route.

**Comment by allthesignals** [comment]
Issue moved to [NYCPlanning/labs-home #78](https://github.com/NYCPlanning/labs-home/issues/78) via [**ZenHub**](https://www.zenhub.com/)
